version: '1.0'
 
services:
  app:
    container_name: lipsync_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app  # Maps the current directory to /app in the container
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all  # Use all GPUs; set a number to restrict
    #           capabilities: [gpu]
    # runtime: nvidia
    # command: ["uvicorn", "main_old:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]